"""Unit tests for the `ingestion` pipeline nodes.

The fixture workbook is generated by the ``sample_xlsx`` fixture below
into a pytest temp directory at collection time (a real file is created
on disk so ``pd.read_excel`` can open it), so it always matches exactly
what the tests expect and is never committed. Using the exact sheet
names from the published Online Retail II workbook keeps the test close
to production behaviour; the file itself only carries a handful of rows
so the test stays fast.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd
import pytest

from commerce_signals.pipelines.ingestion.nodes import (
    EXPECTED_SHEETS,
    load_source_to_raw_transactions,
    verify_ingestion_row_count,
)


@pytest.fixture(scope="module")
def sample_xlsx(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Generate a tiny two-sheet Online Retail II-shaped workbook.

    Written into a pytest-owned temp directory (never committed, cleaned
    up by pytest). Reused across tests; ``scope="module"`` so the file
    is written once per test run.
    """
    sample_xlsx = tmp_path_factory.mktemp("fixtures") / "online_retail_ii_sample.xlsx"
    sheet_2009 = pd.DataFrame(
        {
            "Invoice": ["536365", "536366", "536367"],
            "StockCode": ["85123A", "71053", "84406B"],
            "Description": ["WHITE HANGING HEART", "WHITE METAL LANTERN", "CREAM CUPID HEARTS"],
            "Quantity": [6, 6, 8],
            "InvoiceDate": pd.to_datetime(
                [
                    "2009-12-01 07:45:00",
                    "2009-12-01 07:46:00",
                    "2009-12-01 08:00:00",
                ]
            ),
            "Price": [2.55, 3.39, 2.75],
            "Customer ID": [17850.0, 17850.0, 13047.0],
            "Country": ["United Kingdom", "United Kingdom", "United Kingdom"],
        }
    )
    sheet_2010 = pd.DataFrame(
        {
            "Invoice": ["536370", "536372"],
            "StockCode": ["84029G", "84029E"],
            "Description": ["KNITTED UNION FLAG", "RED WOOLLY HOTTIE WHITE HEART"],
            "Quantity": [12, 1],
            "InvoiceDate": pd.to_datetime(
                ["2010-12-01 10:01:00", "2010-12-01 10:05:00"]
            ),
            "Price": [3.39, 5.95],
            "Customer ID": [13047.0, 13047.0],
            "Country": ["United Kingdom", "United Kingdom"],
        }
    )
    with pd.ExcelWriter(sample_xlsx, engine="openpyxl") as writer:
        sheet_2009.to_excel(writer, sheet_name=EXPECTED_SHEETS[0], index=False)
        sheet_2010.to_excel(writer, sheet_name=EXPECTED_SHEETS[1], index=False)
    return sample_xlsx


def test_load_source_concatenates_both_sheets(sample_xlsx: Path) -> None:
    """Both sheets are read and concatenated with ``ignore_index=True``."""
    df, row_counts = load_source_to_raw_transactions(str(sample_xlsx))

    assert row_counts["sheet_2009_2010"] == 3
    assert row_counts["sheet_2010_2011"] == 2
    assert row_counts["total"] == 5
    assert len(df) == 5

    # Column names preserved as-is (no renaming, no typing).
    assert "Invoice" in df.columns
    assert "Customer ID" in df.columns
    # Values from both sheets present in the concatenated frame.
    # Cast to str to avoid a pandas int-vs-str surprise on the Invoice column.
    assert set(df["Invoice"].astype(str).tolist()) == {
        "536365", "536366", "536367", "536370", "536372"
    }


def test_load_source_falls_back_to_positional_sheets(
    sample_xlsx: Path, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """If sheet names don't match, the first two sheets are read by position."""
    renamed = tmp_path / "renamed_sheets.xlsx"
    sheet_2009 = pd.DataFrame({"col": [1, 2]})
    sheet_2010 = pd.DataFrame({"col": [3]})
    with pd.ExcelWriter(renamed, engine="openpyxl") as writer:
        sheet_2009.to_excel(writer, sheet_name="Some Other Name", index=False)
        sheet_2010.to_excel(writer, sheet_name="Yet Another Name", index=False)

    with caplog.at_level(logging.WARNING, logger="commerce_signals.pipelines.ingestion.nodes"):
        df, row_counts = load_source_to_raw_transactions(str(renamed))

    # Fallback produced all three rows from the first two sheets.
    assert len(df) == 3
    assert row_counts["total"] == 3
    # The fallback warning is loud, with the actual sheet names visible.
    assert any("Falling back to the first two sheets" in rec.message for rec in caplog.records)


def test_verify_logs_info_on_match(
    sample_xlsx: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Matching counts log at INFO and never raise."""
    df, row_counts = load_source_to_raw_transactions(str(sample_xlsx))

    with caplog.at_level(logging.INFO, logger="commerce_signals.pipelines.ingestion.nodes"):
        # Should not raise.
        verify_ingestion_row_count(df, row_counts)

    assert any(
        "Ingestion verification OK" in rec.message and rec.levelno == logging.INFO
        for rec in caplog.records
    )


def test_verify_logs_warning_on_mismatch(
    sample_xlsx: Path, caplog: pytest.LogCaptureFixture
) -> None:
    """Mismatched counts log at WARNING; the pipeline does not fail."""
    df, row_counts = load_source_to_raw_transactions(str(sample_xlsx))

    # Simulate the Mongo side losing one row (e.g. failed batch).
    truncated_df = df.iloc[:-1].reset_index(drop=True)

    with caplog.at_level(logging.WARNING, logger="commerce_signals.pipelines.ingestion.nodes"):
        # Must NOT raise.
        verify_ingestion_row_count(truncated_df, row_counts)

    assert any(
        "MISMATCH" in rec.message and rec.levelno == logging.WARNING
        for rec in caplog.records
    )
